---
title: "Forecasting and Time Series Analysis Using R"
author: "Illarion  Jabine"
date: "3/4/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


### 1. Required packages:

* forecast: Methods and tools for displaying and analysing univariate time series forecasts including exponential smoothing via state space models and automatic ARIMA modelling.
* xts: Extensible time series class that provides uniform handling of many R time series classes by extending zoo.
* astsa: Applied Statistical Time Series Analysis
* corrplot: A graphical display of a correlation matrix or general matrix. It also contains some algorithms to do matrix reordering.
* PerformanceAnalytics: Econometric Tools for Performance and Risk Analysis
* TTR: Technical Trading Rules


### 2. Key terms
 * Forecast 
 * Time Series
 * Forecasting Steps

### 3. Useful Links & books
 $ <https://cran.r-project.org/web/views/TimeSeries.html>: CRAN Task View: Time Series Analysis
 $ <https://otexts.com/fpp2/> and <https://otexts.com/fpp3/>: Forecasting: Principles and Practice by Rob J Hyndman and George Athanasopoulos
 $ <https://www.stat.pitt.edu/stoffer/tsda/>
 $ <https://www.crcpress.com/Time-Series-A-Data-Analysis-Approach-Using-R/Shumway-Stoffer/p/book/9780367221096>: Time Series: A Data Analysis Approach Using R by Robert Shumway, David Stoffer
 $ <https://github.com/joshuaulrich/xts>: Github of the xts package creator. 
 
### 4. Introduction
 The main objective of this exercise is to build the robust and flexible sales forecasting process for on-line distribution business. For this purpose as a data source the detailed extract of sales transactions for several years and product hierarchy will be used. I will try to build detailed and aggregated forecasts using different approaches.
 
 Forecasting is widely used statistical task in business that helps to predict the future as accurately as possible, given all of the information available, including historical data and knowledge of any future events that might impact the forecasts (Hyndman et al).
Forecasting can be described as a process of predicting or estimating how the sequence of observations (collected at certain time intervals, regular or irregular) will continue into the future. This process uses past and present data and heavily relies on time series, trend or temporal (as opposed to cross-sectional data collected at a single point in time) analysis.  
There are short/medium/long-term forecasts.
Risk is central to forecasting and indicate the degree of uncertainty or accuracy attached to forecasts. Some things like electricity consumption can naturally be easier to forecast than others (stock price).
According to Hyndman et al the predictability of an event depends on several factors:
 1. how well we understand the factors that contribute to it;
 2. how much data is available;
 3. whether the forecasts can affect the thing we are trying to forecast.
Time series plays a fundamental role in forecasting. Time series can be defined as series of data observed over time. Anything that is observed sequentially over time is a time series. When forecasting time series data, the aim is to estimate how the sequence of observations will continue into the future.

Time series can exhibit certain patterns.
 1. Trend: a pattern exists involving a long-term increase or decrease in
the data. Trend can be linear or non-linear.
 
 2. Seasonal: 
 A periodic pattern exists due to the calendar, e.g. the quarter, month, or day of the week. 
 In this case a time series is affected by seasonal factors such as the time of the year or the day of the week. Seasonality is always of a fixed and known frequency.
Examples are numerous, demand for electricity can have a daily seasonality, whereas ice cream consumption fluctuates with yearly seasonality, i.e. much more consumed in the summer. Perhaps consumption of bread does not depend on callendar seasonality.
Understanding of seasonality comes with the subject domain knowledge, because in different industries or market segments different seasonality may exist.
 
 3. Cyclic: 
 A pattern exists where the data exhibits rises and falls that are not of fixed period or frequency (duration usually of at least 2 years). These fluctuations are also known as “business cycle”, because they believe it's due to economic conditions.
 Do not confuse cycle with season, they are different. Cyclic is a fluctuation of not fixed frequency. If the frequency is constant and related to some aspect of the calendar, then the pattern is seasonal. Hyndman argues that the average length of cycles is longer than the length of a seasonal pattern, and the magnitudes of cycles tend to be more variable than the magnitudes of seasonal patterns.
 
It can be reasonable to assume that some aspects of the past patterns will continue into the future with a certain degree of assumptions. Before choosing a time series model, we need to understand the time series patterns in the data and incorporate them into the model.
Time series models used for forecasting include decomposition models, exponential smoothing models and ARIMA models.


### 5. Forecasting Steps

According to Hyndman and Athanasopoulos the forecasting process can be divided into 5 major steps (steps 3 to 5 will be covered in separate manuals):

5.1. Problem definition
  This step requires an understanding of the way the forecasts will be used, who requires the forecasts, and how the forecasting function fits within the organisation. At this stage the granularity of the forecasts are defined, e.g. every product/outlet line, or for groups of products/outlets, weekly or monthly data. It is also necessary to consider the forecasting horizon. How frequently are forecasts required? Frequent forecasts can be done using an automated system.
  
5.2. Gathering information
  A large part of a forecaster’s time can be spent in locating and collating the available data prior to developing suitable forecasting methods. The data may include sales records of a company, the historical demand for a product, or the unemployment rate for a geographic region.
  
5.3. Exploratory analysis
  As Hyndman et al argue always start by graphing the data. The graphical representation allows quickly to see patterns in the data. With a graph one can easily spot significant trends, assess if seasonality is important or find a presence of business cycles.
  
5.4. Choosing and fitting models
The simplest time series forecasting model uses only information on the variable to be forecast, and make no attempt to discover other factors that affect its behaviour. Therefore they will extrapolate trend and seasonal patterns, but they ignore all other information (Hyndman et al).
Example can be a time series model for forecasting where prediction of the future is based on past values of a variable, but not on external variables which may affect the system: y(t) = f(y(t-1),y(t-2),...) + e
Explanatory model on the contrary helps explain what causes the variation in the variable by including other variables (predictor variables) and building the relationship between them. Example can be a regression model: y = f(x) + e. An explanatory model is useful because it incorporates information about other variables, rather than only historical values of the variable to be forecast.
The major types of models include:
 1. Regression models
 2. Exponential smoothing methods
 3. Box-Jenkins ARIMA models
 4. Dynamic regression models
 5. Hierarchical forecasting
 6. Neural networks and vector autoregression

5.5. Using and evaluating a forecasting model
 Once a model has been selected and its parameters estimated, the model is used to make forecasts.
